# Generated by Django 4.2.5 on 2023-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hash_code',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
